import { WiDaySunny, WiHot, WiSleet, WiSnow, WiThunderstorm, WiDayFog, WiDayCloudy, WiStrongWind, WiDaySunnyOvercast, WiRain, WiCloudy, WiFog, WiSnowflakeCold, WiShowers, WiRainMix, WiDayShowers, WiNightFog, na } from 'weather-icons-react';

export const Icons = {
    "Sunny": WiDaySunny,
    "Mostly sunny": WiDaySunnyOvercast,
    "Partly sunny": WiDayCloudy,
    "Intermittent clouds": WiCloudy,
    "Hazy sunshine": WiDayFog,
    "Mostly cloudy": WiDayCloudy,
    "Partly cloudy": WiDaySunnyOvercast,
    "Cloudy": WiCloudy,
    "Dreary (overcast)": WiFog,
    "Fog": WiFog,
    "Showers": WiShowers,
    "Mostly cloudy w/ showers": WiDayShowers,
    "Partly cloudy w/ showers": WiDayShowers,
    "Partly sunny w/ showers": WiDayShowers,
    "T-storms": WiThunderstorm,
    "Mostly cloudy w/ t-storms": WiThunderstorm,
    "Partly cloudy w/ t-storms": WiThunderstorm,
    "Partly sunny w/ t-storms": WiThunderstorm,
    "Rain": WiRain,
    "Flurries": WiSnow,
    "Mostly cloudy w/ flurries": WiSnow,
    "Partly sunny w/ flurries": WiSnow,
    "Snow": WiSnow,
    "Mostly cloudy w/ snow": WiSnow,
    "Ice": WiSnowflakeCold,
    "Sleet": WiSleet,
    "Freezing rain": WiRainMix,
    "Rain and snow": WiRainMix,
    "Hot": WiHot,
    "Cold": WiSnowflakeCold,
    "Windy": WiStrongWind,
    "Clear": WiDaySunny,
    "Mostly clear": WiDaySunny,
    "Hazy moonlight": WiNightFog,
    "Thunderstorms": WiThunderstorm
};
